# install-cloudflared.ps1
# Installs and configures Cloudflare Tunnel (cloudflared) on Windows
# Run as Administrator

#Requires -RunAsAdministrator

param(
    [switch]$SkipInstall,
    [switch]$Help
)

if ($Help) {
    Write-Host @"
Cloudflared Installation Script
================================

Usage:
    .\install-cloudflared.ps1              # Full install
    .\install-cloudflared.ps1 -SkipInstall # Skip winget, just configure

This script will:
1. Install cloudflared via winget
2. Guide you through authentication
3. Create a tunnel
4. Set up DNS routes
5. Install as Windows service

"@
    exit 0
}

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Cloudflare Tunnel Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Install cloudflared
if (-not $SkipInstall) {
    Write-Host "[1/6] Installing cloudflared..." -ForegroundColor Yellow

    $installed = Get-Command cloudflared -ErrorAction SilentlyContinue
    if ($installed) {
        Write-Host "  cloudflared already installed: $($installed.Source)" -ForegroundColor Green
        cloudflared --version
    } else {
        Write-Host "  Installing via winget..." -ForegroundColor Gray
        winget install Cloudflare.cloudflared --accept-source-agreements --accept-package-agreements

        # Refresh PATH
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

        Write-Host "  Installed successfully!" -ForegroundColor Green
        cloudflared --version
    }
} else {
    Write-Host "[1/6] Skipping installation..." -ForegroundColor Gray
}

Write-Host ""

# Step 2: Authenticate
Write-Host "[2/6] Authenticating with Cloudflare..." -ForegroundColor Yellow

$certPath = "$env:USERPROFILE\.cloudflared\cert.pem"
if (Test-Path $certPath) {
    Write-Host "  Already authenticated (cert.pem exists)" -ForegroundColor Green
    $reauth = Read-Host "  Re-authenticate? (y/N)"
    if ($reauth -eq 'y') {
        cloudflared tunnel login
    }
} else {
    Write-Host "  Opening browser for authentication..." -ForegroundColor Gray
    Write-Host "  Select your domain when prompted." -ForegroundColor Gray
    cloudflared tunnel login
}

Write-Host ""

# Step 3: Create tunnel
Write-Host "[3/6] Creating tunnel..." -ForegroundColor Yellow

$tunnelName = "ra-services"
$existingTunnel = cloudflared tunnel list --output json 2>$null | ConvertFrom-Json | Where-Object { $_.name -eq $tunnelName }

if ($existingTunnel) {
    Write-Host "  Tunnel '$tunnelName' already exists: $($existingTunnel.id)" -ForegroundColor Green
    $tunnelId = $existingTunnel.id
} else {
    Write-Host "  Creating tunnel '$tunnelName'..." -ForegroundColor Gray
    $output = cloudflared tunnel create $tunnelName 2>&1
    Write-Host $output

    # Get the tunnel ID
    $tunnelInfo = cloudflared tunnel list --output json | ConvertFrom-Json | Where-Object { $_.name -eq $tunnelName }
    $tunnelId = $tunnelInfo.id
    Write-Host "  Tunnel created with ID: $tunnelId" -ForegroundColor Green
}

Write-Host ""

# Step 4: Get domain info
Write-Host "[4/6] Configuring routes..." -ForegroundColor Yellow

$domain = Read-Host "  Enter your domain (default: selfwize.com)"
$tenant = Read-Host "  Enter tenant/org name (default: ra)"
$snipeitSubdomain = Read-Host "  Enter subdomain for Snipe-IT (default: snipe)"
$fastenSubdomain = Read-Host "  Enter subdomain for Fasten Health (default: fasten)"

if ([string]::IsNullOrWhiteSpace($domain)) { $domain = "selfwize.com" }
if ([string]::IsNullOrWhiteSpace($tenant)) { $tenant = "ra" }
if ([string]::IsNullOrWhiteSpace($snipeitSubdomain)) { $snipeitSubdomain = "snipe" }
if ([string]::IsNullOrWhiteSpace($fastenSubdomain)) { $fastenSubdomain = "fasten" }

$snipeitHost = "$snipeitSubdomain.$tenant.$domain"
$fastenHost = "$fastenSubdomain.$tenant.$domain"

Write-Host ""
Write-Host "  Snipe-IT will be at: https://$snipeitHost" -ForegroundColor Cyan
Write-Host "  Fasten will be at:   https://$fastenHost" -ForegroundColor Cyan
Write-Host ""

# Step 5: Create config file
Write-Host "[5/6] Creating configuration..." -ForegroundColor Yellow

$configDir = "$env:USERPROFILE\.cloudflared"
$configPath = "$configDir\config.yml"
$credentialsPath = "$configDir\$tunnelId.json"

$configContent = @"
# Cloudflare Tunnel Configuration
# Generated by install-cloudflared.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

tunnel: $tunnelId
credentials-file: $credentialsPath

ingress:
  # Snipe-IT Asset Management
  - hostname: $snipeitHost
    service: http://192.168.68.56:8082
    originRequest:
      noTLSVerify: true

  # Fasten Health
  - hostname: $fastenHost
    service: http://192.168.68.56:9090
    originRequest:
      noTLSVerify: true

  # Catch-all (required)
  - service: http_status:404
"@

$configContent | Out-File -FilePath $configPath -Encoding utf8 -Force
Write-Host "  Config written to: $configPath" -ForegroundColor Green

# Create DNS routes
Write-Host "  Creating DNS routes..." -ForegroundColor Gray
cloudflared tunnel route dns $tunnelName $snipeitHost 2>&1
cloudflared tunnel route dns $tunnelName $fastenHost 2>&1
Write-Host "  DNS routes created" -ForegroundColor Green

Write-Host ""

# Step 6: Validate and test
Write-Host "[6/6] Validating configuration..." -ForegroundColor Yellow

cloudflared tunnel ingress validate
if ($LASTEXITCODE -eq 0) {
    Write-Host "  Configuration is valid!" -ForegroundColor Green
} else {
    Write-Host "  Configuration has errors. Please check $configPath" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Setup Complete!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Test the tunnel (Ctrl+C to stop):" -ForegroundColor White
Write-Host "   cloudflared tunnel run ra-services" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Visit your URLs to verify:" -ForegroundColor White
Write-Host "   https://$snipeitHost" -ForegroundColor Cyan
Write-Host "   https://$fastenHost" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. Install as Windows service (run as Admin):" -ForegroundColor White
Write-Host "   cloudflared service install" -ForegroundColor Gray
Write-Host ""
Write-Host "4. Set up Cloudflare Access (authentication):" -ForegroundColor White
Write-Host "   https://one.dash.cloudflare.com" -ForegroundColor Cyan
Write-Host "   Go to: Access > Applications > Add Application" -ForegroundColor Gray
Write-Host ""
Write-Host "For troubleshooting, see:" -ForegroundColor White
Write-Host "   docs\guides\CLOUDFLARE-TUNNEL-SETUP.md" -ForegroundColor Gray
Write-Host ""
